# @package _global_
defaults:
  - checkpoint: last_k
  - data: default
  - logger: cassini
  - model: default
  - optimizer: adamw
  - trainer: train
  - decode: default
exp_dir: '/home/xx/My_projects/auto_avsr'
exp_name: 'weight'
num_workers: 12
gpus: 4
slurm_job_id: 2  # xx自己写的
train: True
log_wandb: True
infer_path: null
ckpt_path: null
transfer_frontend: null

